### ISSUE TITLE
Legacy pg user / role and extensions are not provided in this image

### ISSUE THREAD

**Issue by MatteoGauthier** [railwayapp-templates/postgres-ssl#1]
Hey Railway team,

I've been using the database provisioning service included with Railway (Postgres) for several months, and recently you've changed your methodology (which is very good) by introducing container services and a volume. However, the new database provisioning solution does not respect your documentation and previous versions...

So here are the changes I detected.

<table>
<tr>
 <td> 
 <td>Legacy
 <td>New postgresql image
<tr>
 <td>Plugins
 <td>timescaledb
 <td>
<tr>
 <td>Role name / User
 <td>postgres
 <td>railway
</table>

This is problematic because nowhere does it say that these properties have changed.

In addition, the documentation is not up to date...
![Capture d’écran 2023-09-29 à 15 48 03](https://github.com/railwayapp-templates/postgres-ssl/assets/32040951/88ab60a0-ba1c-4fff-868c-277135fe378e)

I'm trying to migrate my legacy database to the new ones, but my `pg_restore` are failing due to these changes.

Btw I love your product !!

**Comment by melissa-hale** [comment]
Hey @MatteoGauthier thank you so much for this feedback.  We have updated the default user to `postgres`.

As for timescaledb and postgis extension, we will provide a separate template soon that will include these.

**Comment by ThallesP** [comment]
> Hey @MatteoGauthier thank you so much for this feedback. We have updated the default user to `postgres`.
> 
> As for timescaledb and postgis extension, we will provide a separate template soon that will include these.

Will that be a separate template for each one? Because we use `timescale + postgis` and i don't want to deal with forks.

**Comment by melissa-hale** [comment]
Shoot I'm so sorry @ThallesP I missed your question here.  You probably already found them, but yes we have a separate image and template that includes timescale and postgis.

https://railway.app/template/timescaledb-postgis
https://github.com/railwayapp-templates/timescale-postgis-ssl
