### ISSUE TITLE
Postgres logging to stdout

### ISSUE THREAD

**Issue by sami286** [railwayapp-templates/postgres-ssl#10]
Hi everyone, 

As you know, by default all Postgres logs are written into stderr by default:
![image](https://github.com/railwayapp-templates/postgres-ssl/assets/11246472/2b156783-ceac-40da-8dc7-7dc870555013)

This can led to some comprehension issues when reading logs from Railway's observability tab as they are being worngly classified and displayed as erros:
![image](https://github.com/railwayapp-templates/postgres-ssl/assets/11246472/2201d07e-a3eb-4224-8719-8600c84582ef)

I think it would be nice if Railway Postgres image had logs written to stdout by default, so that de web UI would render them as info logs :)

(If this idea sounds good to you, I can propose a PR for it)

**Comment by melissa-hale** [comment]
I love this idea @sami286 , PR is welcome.  It'd be really great to make it configurable with an environment variable if possible

**Comment by sami286** [comment]
Hi @melissa-hale, I created a PR to make this behaviour configurable with an environment variable :)
You can have a look at it here #11

**Comment by melissa-hale** [comment]
@sami286 again, tremendous apologies for leaving you hanging forever.  I very much appreciate the contribution and have merged in your PR!  thank you again and please keep 'em coming (I promise it won't take so long for a review next time)

**Comment by sami286** [comment]
Thanks @melissa-hale, I love to help a bit whenever I can 😊
