### ISSUE TITLE
Modify the datestyle

### ISSUE THREAD

**Issue by giandepaoli** [railwayapp-templates/postgres-ssl#12]
Hello to everyone.

Im using postgresql image into railway for stage/dev NodeJS apps. This apps have migrations files with datestyle DMY, which is inconsistent with the default datestyle (assuming is MDY). 

Is any way to change this? Using ENV or somehow changing the postgresql.config file?

Thanks!

**Comment by brody192** [comment]
Hey, this question would pertain more to Postgres itself than it would the template, please review how Postgres would have you change this.
